### ISSUE TITLE
Delete stale branches

### ISSUE THREAD

**Issue by dac514** [Izumi-kun/LTI-Tool-Provider-Library-PHP#12]
I watch this repo as the authority for LTI-Tool-Provider-Library-PHP. 

Two emails came in about pull requests and it took me a few minutes to figure out where the PRs were coming from (Because it's the morning and I need a coffee? They're coming from markn86 and not this repo?)

It would have been less confusing if the stale branches were deleted.

![image](https://user-images.githubusercontent.com/812192/41974735-be6fff5a-79e6-11e8-8669-0f93b1f1fd70.png)

_Keep master because it's origin, or maybe rename origin, etc._

Thank you for your consideration.

**Comment by Izumi-kun** [comment]
Stale branches exists only for my PRs to origin repo.
Agree with renaming default branch to master and current master to origin.

New PRs is created from markn86 repo by me for potential merging.

**Comment by dac514** [comment]
> Stale branches exists only for my PRs to origin repo.

Ugh, right. The "official" repo will merge these any day now. :)

Ok all good.

**Comment by Izumi-kun** [comment]
In truth, I do not believe that these PRs will be accepted. So i plan to remove stale branches and close my PRs in origin repo in near future.
