### ISSUE TITLE
Tool Provider Private Methods

### ISSUE THREAD

**Issue by jkm9000** [Izumi-kun/LTI-Tool-Provider-Library-PHP#19]
Hello, thanks for this fork. I'm doing my first implementation of LTI and was glad to come across this since the original is now abandoned.

I am trying to integrate this into an existing Symfony application and it's a bit of a challenge using the ToolProvider class. I'm still very early on but what's hanging me up comes down to being unable to override some of these private methods.

For example, `result()` directly calls `header()` to redirect, and other times it does inline echo statements. That makes it very hard to try and pass data to views, add logging, etc.

At first I thought about using output buffering to capture the echos but the inline `header()` calls make that problematic.

I could just fork this repository and handle it that way, but I thought maybe others could benefit. Is there a good reason to keep these private? Has anyone else integrated this into a framework like Symfony and worked around this in other ways?

Thanks much!

**Comment by Izumi-kun** [comment]
In current implementation you can override `handleRequest` method and replace `result` call with something you needed.

**Comment by jkm9000** [comment]
Thanks. Unfortunately, authenticate() is also a private method so looks like I would have to implement that as well. If these methods were protected instead, it would be a lot easier to work with.

If that's not something you're willing to do, I can always just make a fork.

**Comment by Izumi-kun** [comment]
Agree. PR is merged. Thanks!

**Comment by jkm9000** [comment]
Great, thanks!
